title:            Tarsis Azevedo
tagline:          Sobre programação, web e tudo mais.
description:      Sobre programação, web e tudo mais.
#Comment out url when working locally to resolve base urls correctly
url: http://blog.tarsisazevedo.com

# Owner/author information
owner:
  name:           Tarsis Azevedo
  avatar:         avatar.png
  bio:            "Aesthete & Athlete"
  email:          tarsis.azevedo@gmail.com
  twitter:        tarsisazevedo
  github:         tarsis
  disqus:         blogtarsisazevedo


# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: http://tarsisazevedo.com
    external: true
  - title: Github
    url: https://github.com/tarsis
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Sao_Paulo
future:      true
pygments:    true
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
